---
title: "Git & GitHub"
format: revealjs
---


## Why git?
::: {.incremental}
- A highly controllable backup system.

- Modularisation with branches.

- Collaborative work.

- It's a scientific journal with minimal effort. 
:::


## What can HDRs put under version control?

::: {.incremental}
- Thesis.

- Notes and other writing.

- Any code you write.

- Packages arising from your project. 

- Any config files for productivity apps, text editors, IDE's etc. 
:::

## So what is GitHub?

::: {.incremental}

- Online service for hosting git repositories.

- (Mostly) free.

- Good integration with things like Visual Studio Code and Overleaf.

:::

# Let's create a repository



## The git workflow

0. (Update from remote)

1. Make changes.

2. `add` the changed files.

3. `commit` the staged files.

4. `push` the commit.

# A demo


## Gitignore

Anything you do not want to be tracked goes into the `.gitignore` file.

. . .

- Data and output

- Virtual environments, e.g. `venv/`

- Generated files, e.g. 
`.aux`, `.log`, `__pycache__/`, `.RHistory`

- `.DS_Store`

. . . 

Useful templates: [https://github.com/github/gitignore]()



# IDE integration (and GUI's)

## GUI's 

A GUI is an app we can work with Github and easily visualise what's going on.

. . . 

- Popular free alternative is Github Desktop.
- A popular (and unfortunately less free) version is Gitkraken.

. . . 

## IDE's

Most modern text editors / IDE's are extensible and include a way of integrating git and source control with them.

. . . 

- VScode: Gitlens.
- RStudio: Need to turn source control on.
- Sublime text: Several ways to implement source control.
- Vim: Plugins to emulate the functionality in VScode.
- Emacs: Same as vim but separate because Emacs.

. . . 


# Another demo 
